### ISSUE TITLE
"module' object has no attribute '_lib" when running pathod

### ISSUE THREAD

**Issue by vladvino** [mitmproxy/pathod#22]
Not very familiar with Python. Followed installation instructions but get this when I try to run pathos:

Traceback (most recent call last):
  File "/usr/local/bin/pathod", line 5, in <module>
    cmdline.go_pathod()
  File "/Library/Python/2.7/site-packages/libpathod/cmdline.py", line 381, in go_pathod
    pathod.main(args)
  File "/Library/Python/2.7/site-packages/libpathod/pathod.py", line 394, in main
    certs = args.ssl_certs
  File "/Library/Python/2.7/site-packages/libpathod/pathod.py", line 32, in __init__
    CERTSTORE_BASENAME
  File "/Library/Python/2.7/site-packages/netlib/certutils.py", line 163, in from_store
    dh = cls.load_dhparam(dh_path)
  File "/Library/Python/2.7/site-packages/netlib/certutils.py", line 143, in load_dhparam
    bio = OpenSSL.SSL._lib.BIO_new_file(path, b"r")
AttributeError: 'module' object has no attribute '_lib'

I am on Max OS X 10.10.3 and Python 2.7.9.

**Comment by vladvino** [comment]
Found old thread https://github.com/mitmproxy/mitmproxy/issues/281 and followed advice to rename OpenSSL folder containing version 0.13.
