### ISSUE TITLE
Test failure in 0.12.1

### ISSUE THREAD

**Issue by felixonmars** [mitmproxy/pathod#24]
I am getting the following test failure:

```
........................................................................................................................................................F.................
======================================================================
FAIL: test_pathod.TestDaemonSSL.test_websocket_frame
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/pathod/src/pathod-0.12.1/test/test_pathod.py", line 203, in test_websocket_frame
    assert self.d.last_log()["type"] == "wsframe"
AssertionError:
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/clear_log HTTP/1.1" 200 2
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/log HTTP/1.1" 200 1669
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 170 tests in 10.188s

FAILED (failures=1)
```

All dependencies should be latest.

**Comment by cortesi** [comment]
I'm hunting this down at the moment. Oddly, I can't reproduce this on my dev workstation, but we do see it when Travis runs the test suite.

**Comment by cortesi** [comment]
Issue appears to be fixed.
